blueprint:
  name: Auto Lights Master
  description: The lights will turn on if light level low enough, if after set time, the lights wont turn off again automatically.
  domain: automation
  input:
    light_entity:
      name: Light
      description: The Light Entity to be controlled automatically
      selector:
        entity:
          domain: light
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor which will trigger the light
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_sensor:
      name: Light Sensor
      description: Light Level Sensor
      selector:
        entity:
          domain: sensor
    off_time_threshold:
      name: Auto-Off Time Threshold
      description: The time when the lights will no longer turn off automatically
      selector:
        time:
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 60
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    phone_charge_state:
      name: Phone Charge Sensor
      description: Sensor which tracks phone charging
      

mode: single
max_exceeded: silent
      
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'

condition:
  - condition:  numeric_state
    entity_id: !input light_sensor
    below: 15

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: 'off'
          - condition: time
            after: !input off_time_threshold
            before: '08:00:00'
          - condition: state
            entity_id: sensor.iphone_xr_battery_state
            state: 'Not Charging'
          - condition: state
            entity_id: sensor.zoeys_iphone_battery_state
            state: 'Not Charging'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 50
            target:
              entity_id: !input light_entity
          - wait_for_trigger:
              platform: state
              entity_id: !input phone_charge_state
              to: 'Charging'
          - service: light.turn_off
            data: 
              transition: 5
            target: 
              entity_id: !input light_entity
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: 'off'
          - condition: time
            after: !input off_time_threshold
            before: '08:00:00'
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.iphone_xr_battery_state
                state: 'Not Charging'
              - condition: state
                entity_id: sensor.zoeys_iphone_battery_state
                state: 'Not Charging'
        sequence:
          - wait_for_trigger:
              platform: state
              entity_id: !input motion_sensor
              from: 'on'
              to: 'off'
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: 'off'
          - condition: time
            after: !input off_time_threshold
            before: '08:00:00'
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.iphone_xr_battery_state
                state: 'Not Charging'
              - condition: state
                entity_id: sensor.zoeys_iphone_battery_state
                state: 'Not Charging'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 1
            target:
              entity_id: !input light_entity
          - wait_for_trigger:
              platform: state
              entity_id: !input motion_sensor
              from: 'on'
              to: 'off'
          - service: light.turn_off
            data: 
              transition: 5
            target: 
              entity_id: !input light_entity
    default:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: !input light_entity
      - wait_for_trigger:
          platform: state
          entity_id: !input motion_sensor
          from: "on"
          to: "off"
          for: !input no_motion_wait
      - service: light.turn_off
        target:
          entity_id: !input light_entity

