- platform: iphonedetect
  consider_home: 60
  scan_interval: 12
  new_device_defaults:
    track_new_devices: true
  hosts:
    john_wifi: 192.168.1.22
    maria_wifi: 192.168.1.52
    simon_wifi: 192.168.1.24
    simon_watch: 192.168.1.28
    zoey_wifi: 192.168.1.137
    judi_wifi: 192.168.1.25
    valerie_wifi: 192.168.1.186

#- platform: bluetooth_le_tracker
- platform: bluetooth_tracker