- platform: rest
  resource: !secret zwarteveen_heartbeat
  name: Zwarteveen HeartBeat
  scan_interval: '00:05:00'
  headers:
    Authorization: !secret zwarteveen_credentials
  value_template: >
   {% if value_json is defined and value_json.state is defined %}
     {{ value_json.state }}
   {% else %}
     {{ states('sensor.zwarteveen_heartbeat') }}
   {% endif %}
- platform: rest
  resource: !secret sensor_maria
  name: Maria
  headers:
    Authorization: !secret zwarteveen_credentials
  value_template: '{{ value_json.state }}'
- platform: rest
  resource: !secret sensor_john
  name: John
  headers:
    Authorization: !secret zwarteveen_credentials
  value_template: '{{ value_json.state }}'
- platform: season
- platform: uptime
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: processor_use
    #- type: processor_temperature
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /

- platform: fronius
  resource: !secret fronius_url
  monitored_conditions:
    - sensor_type: inverter
      scope: system
      device: 1
